ValueWithError: two more functions are added
git-svn-id: http://svn.cern.ch/guest/lhcb/LHCb/trunk@196967 4525493e-7705-40b1-a816-d608a930855b

Former-commit-id: bd1de6f2eaf054a1194042e2050702e2bb06cdcd