ValueWithError: two more functions are added
git-svn-id: http://svn.cern.ch/guest/lhcb/LHCb/trunk@196961 4525493e-7705-40b1-a816-d608a930855b

Former-commit-id: d526e91484338359feedc03089532ed6736481e5